import { useState } from "react";
import { useAuth } from "../AuthContext";
import {
  ChevronDown, ChevronUp, Search, BookOpen, LayoutDashboard, Megaphone,
  Calendar, Layers, GraduationCap, Users, UserPlus, Package, Quote,
  Mail, ShieldCheck, Settings, ClipboardList, FileText, Newspaper,
  HelpCircle, Lock, Globe, Phone, Sparkles, Bell, StickyNote,
  Building2, CreditCard,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

type Role = "admin" | "teacher" | "assistant" | "all";

type SpecSection = {
  id: string;
  title: string;
  icon: React.ElementType;
  roles: Role[];
  color: string;
  overview: string;
  steps?: { heading: string; detail: string }[];
  tips?: string[];
  notes?: string[];
};

// ─── Specification data ───────────────────────────────────────────────────────

const SECTIONS: SpecSection[] = [
  {
    id: "auth",
    title: "Login & Authentication",
    icon: Lock,
    roles: ["all"],
    color: "from-slate-500 to-slate-700",
    overview:
      "The portal supports two login methods: email + password for Super Admin, and phone number + 4-digit PIN for teachers and assistants. PINs are auto-generated when a staff member is added in Staff Management. Accounts lock after 5 consecutive wrong PIN entries for 15 minutes.",
    steps: [
      { heading: "Super Admin login", detail: "Navigate to /admin/login. Enter your registered email address and password, then click Sign In." },
      { heading: "Teacher / Assistant login", detail: "On the login page, type your 10-digit phone number (digits only). The form switches to PIN mode automatically. Enter your 4-digit PIN and click Sign In." },
      { heading: "How teachers get their PIN", detail: "PINs are auto-generated by the system when the Admin adds a staff member in Staff Management. The PIN appears once in a green banner — the Admin must copy it and share it securely. After the banner is dismissed, the PIN cannot be retrieved (only reset)." },
      { heading: "Forgot PIN / Reset PIN", detail: "Ask the Admin to click the 🔑 Reset PIN button next to your name in Staff Management. A new PIN will be generated and shown in the banner." },
      { heading: "Change credentials", detail: "Admins change their password from Settings → Change Password. Teachers change their PIN from Settings → Change PIN." },
    ],
    tips: [
      "PINs are 4 numeric digits — do not share them with others.",
      "After 5 wrong PIN attempts the account is locked for 15 minutes automatically.",
      "The login form detects phone vs email input automatically and switches mode.",
      "PINs are bcrypt-hashed in the database — nobody, including admins, can read them after creation.",
    ],
  },
  {
    id: "dashboard",
    title: "Dashboard",
    icon: LayoutDashboard,
    roles: ["admin"],
    color: "from-indigo-500 to-indigo-700",
    overview:
      "The Dashboard is the Admin's home screen, providing a high-level snapshot of the Gurukul's operations — student counts, teacher counts, upcoming events, and recent announcements.",
    steps: [
      { heading: "Access", detail: "Admins are redirected here automatically after login. Teachers and Assistants see Courses & Classes instead." },
      { heading: "Stats cards", detail: "Top cards show total students, active teachers, upcoming events, and today's attendance rate." },
      { heading: "Recent activity", detail: "Scroll down to see the latest announcements and any recently published weekly updates." },
    ],
    tips: ["The Dashboard is a read-only summary — no edits happen here. Use the sidebar links to manage each area."],
  },
  {
    id: "members",
    title: "Member Management",
    icon: Building2,
    roles: ["admin"],
    color: "from-sky-500 to-sky-700",
    overview:
      "Member Management handles the temple membership records that every Gurukul student must be linked to. A student cannot be registered without selecting an active temple member. Members are valid for one year from their join date. Membership status is automatically calculated: Active (within 1 year), Expiring Soon (within 30 days of expiry), or Expired.",
    steps: [
      { heading: "View members", detail: "Go to Member Management. The page loads all members at once with live client-side filtering. Stats at the top show totals: all members, active, expired, members with students, without students, and added this month." },
      { heading: "Filter members", detail: "Use the Status pill buttons (All / Active / Expiring Soon / Expired) to filter by membership health. Use the Students pill buttons (All / With Students / Without Students) to find members who are or aren't linked to any student. Type in the Employer search box to filter by employer name." },
      { heading: "Sort", detail: "Click column headers (ID, Name, Email, Join Date) to sort ascending or descending." },
      { heading: "Add a member", detail: "Click Add Member. Enter name, email, phone (all three mandatory), and optionally a membership year and employer. Click Save — the member is created immediately and can now be linked to students." },
      { heading: "View member detail", detail: "Click the eye (👁) icon on any member row to open a detail panel. The panel shows all member info, membership status with expiry date, and a list of all Gurukul students linked to this member." },
      { heading: "Edit a member", detail: "Click the pencil (✏) icon to update name, email, phone, employer, or membership year. Phone and email are mandatory — you cannot save with either blank." },
      { heading: "Delete a member", detail: "Click the trash (🗑) icon. If the member has any students linked, deletion is blocked — you must remove or re-link those students first." },
      { heading: "Export", detail: "Click Download CSV to export all filtered members to a spreadsheet." },
    ],
    notes: [
      "Every Gurukul student must be linked to a temple member — memberId is mandatory at registration.",
      "Only members with Active status can have new students registered against them.",
      "A member whose membership has Expired can still be viewed and their linked students seen, but no new students can be added under them until membership is renewed.",
      "Membership is calculated as 1 year from the member's join date (createdAt) — there is no manual expiry field.",
      "Members cannot be deleted while they have students linked to them.",
    ],
    tips: [
      "Check 'Expiring Soon' regularly and remind families to renew their temple membership before it lapses.",
      "Use the 'Without Students' filter to find temple members who have not yet enrolled any children — a useful outreach list.",
      "Phone and email are both mandatory for members since the parent portal uses phone verification.",
    ],
  },
  {
    id: "registration",
    title: "Student Registration",
    icon: UserPlus,
    roles: ["admin"],
    color: "from-emerald-500 to-emerald-700",
    overview:
      "Student Registration is the form used to admit new students into the Gurukul and enrol them in a course section. Every student must be linked to an active temple member record (the member represents the family). Once registered, the student is visible in Student Management and appears in the teacher's attendance roster.",
    steps: [
      { heading: "Open the form", detail: "Go to Student Registration in the sidebar, or click the + Register Student button from the Student Management page. The form opens as a slide-over panel." },
      { heading: "Link to a temple member (mandatory)", detail: "Start typing the family's name or phone in the Member search box. Select the matching active member from the dropdown. This links the student to the family's temple membership. Only Active members appear — Expired memberships must be renewed first." },
      { heading: "Enter student details", detail: "Fill in: Student Name, Date of Birth, Grade (school grade level), Curriculum Year, and check 'New Student' if this is their first year at the Gurukul." },
      { heading: "Enter parent contacts", detail: "Fill in mother and father details separately — each has their own Name, Phone, and Email fields. Both sets are optional but at least one contact is strongly recommended for communication purposes." },
      { heading: "Choose enrollment", detail: "Select Course → Level → Section using the cascading dropdowns. The section automatically determines the assigned teacher. You can leave section blank if class placement is still pending." },
      { heading: "Set payment details", detail: "Enter the fee Amount Due, Amount Paid (0 if not yet paid), Payment Method (Cash / Check / Online / Waived), and an optional Receipt ID." },
      { heading: "Submit", detail: "Click Register Student. The student immediately appears in Student Management and in the teacher's class roster for attendance." },
    ],
    notes: [
      "A temple member link (memberId) is required — you cannot save a registration without selecting a member.",
      "Only members with Active membership status can be selected. Expired members are excluded from search results.",
      "A single member (family) can have multiple students registered under them.",
    ],
    tips: [
      "Register the temple membership first (in Member Management) before trying to register a student.",
      "Double-check phone numbers — parents use their phone number to verify identity on the Parent Portal.",
      "You can register a student without a section if class placement is still being decided — just update their enrollment later from Student Management.",
    ],
  },
  {
    id: "students",
    title: "Student Management",
    icon: Users,
    roles: ["admin"],
    color: "from-green-500 to-green-700",
    overview:
      "Student Management gives the Admin a complete view of all enrolled students across courses, with their parent contacts, payment status, and enrollment details. You can filter, sort, bulk-manage, view payment breakdowns, and export student data from this page.",
    steps: [
      { heading: "View students", detail: "The page loads all students at once. The table shows: Student Code, Name, Grade, Course, Level, Section, Parent Contact (M/F rows), Payment summary, Active status, and actions." },
      { heading: "Filter", detail: "Use the filter panel (funnel icon) to narrow by: Course, Level, Section, Payment Status (Paid/Pending/Overdue), Active Status (Active/Inactive), and Curriculum Year." },
      { heading: "Sort", detail: "Click any sortable column header — ID, Name, Grade, Course, Level, Payment Status, Total Paid, or Active — to sort ascending/descending." },
      { heading: "Parent Contact column", detail: "The Parent Contact column shows two rows per student: M (mother, in pink) with phone and email, and F (father, in blue) with phone and email. If a parent's contact is missing, that row is hidden." },
      { heading: "View payment details", detail: "Click anywhere on a student's Payment cell to open the Payment Details slide-over. It shows a card per enrollment with: Course, Level, Section, Timing, Payment Status badge, Amount Due / Paid / Balance boxes, Payment Method, Receipt #, and Enrollment Date. The footer shows the total Due, Paid, and Balance across all enrollments." },
      { heading: "Edit a student", detail: "Click the pencil (✏) icon to open the Edit Student panel. Update personal info, parent contacts, enrollment details, payment amounts, method, and receipt." },
      { heading: "Mark active / inactive", detail: "Click the UserX / UserCheck icon on a student row to toggle their active status individually. Inactive students appear dimmed in all views." },
      { heading: "Bulk actions", detail: "Check the box on multiple student rows (or check the header to select all on the current page). Use the bulk action bar that appears to: Mark Active, Mark Inactive, or Delete selected students." },
      { heading: "Export", detail: "Click the Download CSV icon to export all currently-filtered students to a CSV file with all columns including parent contacts." },
      { heading: "Search", detail: "Type in the search box to instantly filter students by name or student code." },
    ],
    notes: [
      "Every student is linked to a temple member — the member link is permanent after registration and can only be changed by editing the student.",
      "Deleting a student permanently removes all their enrollments, attendance records, and payment history. This cannot be undone.",
      "Inactive students remain in the system and in all historical records — they are just hidden from active views.",
    ],
    tips: [
      "Use the Payment cell click to quickly check a family's balance without leaving the student list.",
      "The Payment column is sortable — sort by 'Payment Status' to surface all Overdue students at once.",
      "Bulk-select Inactive students and use 'Mark Active' to re-enroll returning students at the start of a new year.",
      "The CSV export respects your current filters — filter first to export a specific class or payment group.",
    ],
  },
  {
    id: "course-management",
    title: "Course Management",
    icon: Layers,
    roles: ["admin"],
    color: "from-violet-500 to-violet-700",
    overview:
      "Course Management is where the Admin builds the complete class structure. The hierarchy is: Course → Level → Section. Everything else (teachers, students, attendance, weekly updates) is tied to this structure.",
    steps: [
      { heading: "Create a Course", detail: "Go to Course Management. Click Add Course. Enter the course name (e.g. Hindi, Sanskrit, Dharma, Telugu, Gujarati) and save." },
      { heading: "Add Levels", detail: "Under each course, add levels such as Beginner, Intermediate, Advanced, or Level 1, Level 2, etc. Levels represent the progression within a course." },
      { heading: "Add Sections", detail: "Under each level, add sections — these are the actual class batches (e.g. Section A on Saturdays 10 AM, Section B on Sundays 2 PM). Each section has its own enrolled students and assigned teacher." },
      { heading: "Edit or Archive", detail: "You can rename courses, levels, and sections at any time. Deleting a section will remove its attendance records, so archive rather than delete when possible." },
    ],
    tips: [
      "Plan your structure before adding teachers and students — changes later can be disruptive.",
      "Sections are the smallest unit — each has one teacher and one group of students.",
      "You can have multiple sections under the same level for different time slots.",
    ],
  },
  {
    id: "teachers",
    title: "Staff Management",
    icon: GraduationCap,
    roles: ["admin"],
    color: "from-blue-500 to-blue-700",
    overview:
      "Staff Management is where you add, edit, and assign teachers and teaching assistants. Adding a staff member automatically creates their portal login account and generates a secure 4-digit PIN — no separate User Management step required.",
    steps: [
      { heading: "Add a teacher", detail: "Click Add Teacher. Enter name, email, phone number, and choose category: Senior Teacher or Assistant. Optionally assign them to a course. Click Save — a portal account and PIN are created automatically." },
      { heading: "Share the PIN", detail: "After saving, a green banner appears at the top of the page showing the new teacher's phone number and generated PIN. Copy the PIN immediately and share it securely with the teacher. The banner disappears when dismissed — the PIN is not stored in readable form anywhere after that." },
      { heading: "Reset PIN", detail: "Click the 🔑 Reset PIN button on the teacher's row. A new PIN is generated instantly and shown in the banner. The old PIN is immediately invalidated." },
      { heading: "Edit assignment", detail: "Click the edit (pencil) icon to change a teacher's name, email, phone, or course assignment." },
      { heading: "Delete a teacher", detail: "Click the trash icon. This removes the teacher from Staff Management and also deletes their portal login account — they will no longer be able to log in." },
    ],
    tips: [
      "The PIN banner disappears when you dismiss it — there is no way to view the PIN again after that. Always copy it first.",
      "Resetting a PIN immediately invalidates the old one — the teacher will be logged out on their next request.",
      "Category 'Senior Teacher' maps to the 'teacher' portal role; 'Assistant' maps to the 'assistant' role.",
      "If a teacher's phone number changes, update it in Staff Management — they use the new number to log in.",
    ],
  },
  {
    id: "inventory",
    title: "Inventory",
    icon: Package,
    roles: ["admin"],
    color: "from-orange-500 to-orange-700",
    overview:
      "The Inventory module helps track physical assets and supplies owned or used by the Gurukul — textbooks, stationery, equipment, ceremonial items, and more.",
    steps: [
      { heading: "Add item", detail: "Click Add Item. Enter the item name, category, current quantity, and any notes." },
      { heading: "Update quantity", detail: "Click the edit icon on an item to adjust the quantity as items are used, restocked, or lost." },
      { heading: "Delete item", detail: "Remove items that are no longer tracked. This is permanent." },
      { heading: "Search", detail: "Use the search bar to quickly find items by name or category." },
    ],
    tips: ["Use categories consistently (e.g. Books, Stationery, Equipment) to make filtering easier.", "Consider adding a note when adjusting quantity to track why the change was made."],
  },
  {
    id: "testimonials",
    title: "Testimonials",
    icon: Quote,
    roles: ["admin"],
    color: "from-pink-500 to-pink-700",
    overview:
      "Testimonials are quotes from parents and students displayed on the public website's homepage and about page. They build trust with prospective families considering enrolment.",
    steps: [
      { heading: "Add testimonial", detail: "Click Add Testimonial. Enter the person's name, their relationship (Parent/Student/Alumni), and their quote." },
      { heading: "Publish / Draft", detail: "Set status to Published to display it on the website. Drafts are saved but not shown." },
      { heading: "Edit or Hide", detail: "Click edit to update the text. Set to Draft to hide without deleting." },
    ],
    tips: ["Keep quotes concise — 2–4 sentences is ideal for readability.", "Use real names (with consent) for authenticity."],
  },
  {
    id: "announcements",
    title: "Announcements",
    icon: Megaphone,
    roles: ["admin"],
    color: "from-rose-500 to-rose-700",
    overview:
      "Announcements are public notices posted on the Gurukul's website, visible to all visitors. Use them for important dates, closures, event notices, or any news you want to share broadly.",
    steps: [
      { heading: "Create", detail: "Click New Announcement. Enter a title, body text, and an optional expiry date. Set status to Published to show it on the website immediately." },
      { heading: "Draft vs Published", detail: "Drafts are saved but not visible publicly. You can edit and publish them later." },
      { heading: "Edit / Delete", detail: "Click the edit (pencil) icon on any announcement to modify it. Deleting removes it from the public site immediately." },
    ],
    tips: ["Set an expiry date for time-sensitive notices so they auto-hide after the event.", "Drafts let you prepare announcements in advance."],
  },
  {
    id: "calendar",
    title: "Events Calendar",
    icon: Calendar,
    roles: ["admin"],
    color: "from-cyan-500 to-cyan-700",
    overview:
      "The Events Calendar lets you manage all Gurukul events that appear on the public website's calendar page — festivals, special classes, exams, closures, and community gatherings.",
    steps: [
      { heading: "Add event", detail: "Click Add Event. Fill in the event name, date, time, location, and a short description. Save to publish it immediately." },
      { heading: "Edit / Delete", detail: "Click any event in the list to edit its details. Delete removes it from the public calendar." },
      { heading: "Public view", detail: "Events appear on the website in chronological order. Past events are shown below upcoming events." },
    ],
    tips: ["Add recurring events (e.g. monthly puja) individually since recurring events are not yet automated.", "Use the Description field to give parents all the details they need."],
  },
  {
    id: "messaging",
    title: "Communication Hub",
    icon: Mail,
    roles: ["admin"],
    color: "from-teal-500 to-teal-700",
    overview:
      "The Communication Hub enables the Admin to send email communications to parents and families. Use it for broadcast notices, fee reminders, or targeted messages to a specific course group.",
    steps: [
      { heading: "Compose message", detail: "Click Compose. Enter a subject and body. Use the recipient filter to choose All families, or target by course/level/section." },
      { heading: "Send", detail: "Click Send. Emails are dispatched immediately using the Gurukul's configured email address (SMTP)." },
      { heading: "View history", detail: "The Sent tab shows all previous messages with timestamps and recipient counts." },
    ],
    notes: ["SMTP must be configured in the server environment for emails to be delivered. Contact the system administrator if emails are not being received."],
    tips: ["Test by sending to yourself first.", "Use specific subject lines so parents don't mistake messages for spam."],
  },
  {
    id: "roles",
    title: "User Management",
    icon: ShieldCheck,
    roles: ["admin"],
    color: "from-red-500 to-red-700",
    overview:
      "User Management shows all portal accounts for teachers and assistants. Teacher and Assistant accounts are created automatically when you add staff in Staff Management — you do not create them manually here. Use this page to review account status, view role assignments, reset PINs, and add portal access for staff who are already in Staff Management.",
    steps: [
      { heading: "View all portal users", detail: "The list shows every portal account for teachers and assistants. Each row shows name, phone, role, and status." },
      { heading: "Add portal access", detail: "Click Add User. Search for an existing staff member (from Staff Management) by name. Select them and choose their role (Teacher or Assistant). A PIN is generated and shown once — copy it immediately." },
      { heading: "Reset PIN", detail: "Click the 🔑 Reset PIN button on any user row. A new PIN is generated and shown in a banner. The old PIN is immediately invalidated." },
      { heading: "Activate / Deactivate", detail: "Toggle a user's active status. Inactive users cannot log in but their account and history are preserved." },
      { heading: "Delete portal access", detail: "Click the trash icon to remove the portal login account. The staff member record in Staff Management is not affected." },
      { heading: "Role permissions reference", detail: "Click the 'Permissions' button to see a full comparison of what each role (Admin / Teacher / Assistant) can access." },
    ],
    notes: [
      "Teacher portal accounts are typically created automatically via Staff Management — only use this page to add portal access for staff added through other means.",
      "To reset a teacher's PIN, you can also use the 🔑 button here or in Staff Management — both work.",
      "PINs are bcrypt-hashed — nobody, including admins, can read them after creation.",
      "Admin (Super Admin) login uses email + password, not a PIN — admin accounts are not listed here.",
    ],
    tips: [
      "Deactivating an account immediately prevents login without deleting any records.",
      "Super Admin is the only account that uses email + password login; all other staff use phone + PIN.",
    ],
  },
  {
    id: "courses",
    title: "Courses & Classes",
    icon: BookOpen,
    roles: ["teacher", "assistant"],
    color: "from-blue-500 to-blue-700",
    overview:
      "Courses & Classes is the teacher's primary view. It shows all courses, levels, and sections with enrolled student rosters. Teachers see all courses; the student search lets you find any student across all courses instantly.",
    steps: [
      { heading: "Browse courses", detail: "Open Courses & Classes in the sidebar. Course cards are shown at the top — click a card to see its levels and student lists." },
      { heading: "Filter by year", detail: "Use the Curriculum Year filter to view classes for a specific academic year." },
      { heading: "View students", detail: "Click a section to see the enrolled student list — name, student code, enrollment status, and parent contact (M/F rows with phone and email). On mobile, parent contact appears inline below the student name." },
      { heading: "Search students", detail: "Click the Search box and start typing. It searches across all courses and sections simultaneously, showing student name, code, enrollment status, course/level, and parent contact." },
    ],
    tips: [
      "If you don't see a section you teach, ask the Admin to verify the enrollment in Student Management.",
      "The parent contact M/F rows let you call or email a student's parents directly from the student list.",
      "Student search is cross-course — useful for finding a student when you don't remember which class they're in.",
    ],
  },
  {
    id: "documents",
    title: "Course Documents",
    icon: FileText,
    roles: ["teacher", "assistant"],
    color: "from-purple-500 to-purple-700",
    overview:
      "Course Documents lets teachers upload and manage learning materials, worksheets, PDFs, reference links, and resources for their classes.",
    steps: [
      { heading: "Select class", detail: "Choose the course and section for the document." },
      { heading: "Upload", detail: "Click Upload Document. Enter a title and description. Either attach a file or paste a URL (Google Doc, YouTube link, etc.)." },
      { heading: "Manage", detail: "Edit or delete documents at any time. Documents are visible to enrolled students if the parent portal sharing is enabled." },
    ],
    tips: ["For large files, use a cloud link (Google Drive, Dropbox) rather than uploading directly.", "Name documents clearly so students and parents can identify them easily."],
  },
  {
    id: "attendance",
    title: "Attendance",
    icon: ClipboardList,
    roles: ["teacher", "assistant"],
    color: "from-green-500 to-green-700",
    overview:
      "Attendance lets teachers record who attended each class session. You can view historical records, see individual student attendance percentages, and generate summaries.",
    steps: [
      { heading: "Select class and date", detail: "Go to Attendance. Choose the course, level, and section. Pick the class date." },
      { heading: "Mark attendance", detail: "For each student, tap Present (✓) or Absent (✗). Add notes for tardiness or early departures if needed." },
      { heading: "Save", detail: "Click Save Attendance. Records are saved immediately." },
      { heading: "View history", detail: "Switch to the History tab to see past attendance records. Filter by date range or student." },
      { heading: "Attendance report", detail: "The report view shows each student's attendance percentage over a selected period — useful for identifying students who need follow-up." },
    ],
    tips: ["Mark attendance promptly after each class while it's fresh.", "Attendance is scoped to your assigned sections — you won't see other teachers' classes.", "Parents can be informed of absences through the Communication Hub (Admin only)."],
  },
  {
    id: "weekly-updates",
    title: "Messaging Center (Weekly Updates)",
    icon: Newspaper,
    roles: ["teacher", "assistant", "admin"],
    color: "from-amber-500 to-amber-700",
    overview:
      "The Messaging Center for teachers has two tabs: Weekly Updates (rich posts you publish each week for parents) and Announcements (school-wide notices from Admin — read-only for teachers). Weekly Updates are the primary way teachers communicate class progress to parents via the Parent Portal.",
    steps: [
      { heading: "Two tabs", detail: "'Weekly Updates' is where you create and manage your class update posts. 'Announcements' shows the latest school-wide notices published by the Admin — read-only for teachers." },
      { heading: "Create a new update", detail: "Click New Update. Use the cascading dropdowns to select Course → Level → Section." },
      { heading: "Set the week period and priority", detail: "Choose the Week Start and Week End dates. Set Priority — High (🔴 urgent, shown prominently on the Parent Portal), Normal, or Low." },
      { heading: "Enter a title", detail: "Write a descriptive title, e.g. 'Week 3 — Introduction to Devanagari Script'." },
      { heading: "Fill content sections", detail: "Class Highlights (required): summary of what happened. Topics Covered, Homework (highlighted in yellow on the Parent Portal), Upcoming Plan, Reminders (highlighted in rose) — optional but strongly recommended." },
      { heading: "Add an attachment", detail: "Paste a link to a Google Doc, YouTube video, or any resource parents should see." },
      { heading: "Save or Publish", detail: "Click Save Draft to save privately, or Publish to make it visible on the Parent Portal immediately. You can edit a published update anytime." },
    ],
    tips: [
      "High Priority updates show a 🔴 badge on the Parent Portal — reserve for truly urgent notices.",
      "Draft updates are only visible to you and admins — parents cannot see them.",
      "You can edit a published update anytime. Changes are reflected on the Parent Portal immediately.",
      "The Announcements tab is read-only — new announcements are created by Admin in the Announcements section.",
    ],
  },
  {
    id: "settings",
    title: "Settings",
    icon: Settings,
    roles: ["all"],
    color: "from-gray-500 to-gray-700",
    overview:
      "Settings lets users change their own login credentials. Admins change their password; Teachers and Assistants change their 4-digit PIN.",
    steps: [
      { heading: "Change Password (Admin)", detail: "Go to Settings. Under Change Password, enter your current password, then the new password twice. Click Update Password." },
      { heading: "Change PIN (Teacher/Assistant)", detail: "Go to Settings. Under Change PIN, enter your current PIN, then the new 4-digit PIN twice. Click Update PIN." },
    ],
    notes: ["Admins cannot change their own PIN here — they use a password.", "Teachers cannot change their own password here — they use a PIN.", "If you forget your current credentials, ask the Admin to reset them from User Management."],
    tips: ["Choose a PIN you can remember but don't share with others.", "Passwords should be at least 8 characters with a mix of letters and numbers."],
  },
  {
    id: "students-corner",
    title: "Student's Corner",
    icon: Sparkles,
    roles: ["all"],
    color: "from-yellow-500 to-orange-500",
    overview:
      "Student's Corner is a public, gamified learning hub on the website at /students-corner. Students can explore 8 courses across two categories — Indian Languages (Hindi, Sanskrit, Telugu, Gujarati, Tamil, Kannada) and Culture & Dharma (Dharma, Music) — through quizzes, memory games, fun facts, and more. No login is required.",
    steps: [
      { heading: "Access", detail: "Students (and anyone) visit the website and click 'Student's Corner' in the navigation. No login is required — it is fully public." },
      { heading: "Choose a course", detail: "The home screen shows two categories: Indian Languages and Culture & Dharma. Select any course to enter its learning hub." },
      { heading: "Explore learning activities", detail: "Each course has interactive activities: quizzes, matching games, fun facts, word searches, and flashcards. Activities are age-appropriate and aligned with the course content." },
      { heading: "Track progress", detail: "Progress (completed activities, scores) is saved in the browser's local storage — no account needed. Students earn badges and see their completion percentage per course." },
      { heading: "Narad Ji", detail: "Narad Ji (the chatbot) appears in Student's Corner with a student-friendly greeting. Students can ask Narad Ji about courses, activities, or anything Gurukul-related." },
    ],
    notes: [
      "Progress is stored locally in the student's browser — clearing browser data will reset progress.",
      "Student's Corner is fully public — no login, no registration required to access it.",
      "Content is designed for students enrolled in the Gurukul but is open to anyone interested.",
    ],
    tips: [
      "Share the /students-corner link directly with parents to encourage students to practise at home.",
      "Narad Ji shows a special student-friendly greeting on the Student's Corner page.",
    ],
  },
  {
    id: "parent-portal",
    title: "Parent Portal",
    icon: Globe,
    roles: ["all"],
    color: "from-orange-500 to-orange-700",
    overview:
      "The Parent Portal is the public-facing section of the Gurukul website at /parents. It gives enrolled families access to Weekly Class Updates after verifying their temple membership via phone number. No app download or account is needed — parents just visit the website.",
    steps: [
      { heading: "Parent accesses the portal", detail: "Parents visit the website and click 'Parents Portal' in the navigation. They see a general overview page with Gurukul information." },
      { heading: "Access Weekly Updates", detail: "Parents click the 'View Weekly Updates' button to enter the gated section." },
      { heading: "Solve captcha", detail: "A simple captcha puzzle prevents automated bot access." },
      { heading: "Phone verification", detail: "Parents enter the phone number registered with their temple membership. If the number matches a record, access is granted for that session." },
      { heading: "View updates", detail: "Parents see all Published weekly updates from teachers, filterable by course. Each card expands to show full details: class highlights, topics covered, homework (highlighted in yellow), upcoming plan, reminders (highlighted in rose), and any attachment links." },
    ],
    notes: [
      "Only Published updates are visible to parents — Drafts remain private to the portal.",
      "High Priority updates display a 🔴 badge so parents immediately spot urgent notices.",
      "Parents cannot log in to edit anything — the portal is completely read-only for families.",
      "Phone verification uses the temple membership database — parents must be registered members with the phone they enter.",
    ],
    tips: [
      "Publish updates regularly — consistent communication keeps parents engaged.",
      "Use the Communication Hub to notify parents when new weekly updates are posted.",
      "For the Student's Corner (gamified learning), share /students-corner — no phone verification needed.",
    ],
  },
];

// ─── Sub-components ───────────────────────────────────────────────────────────

function RolePill({ role }: { role: Role }) {
  const map: Record<Role, { label: string; cls: string }> = {
    admin:     { label: "Admin",     cls: "bg-red-100 text-red-700"    },
    teacher:   { label: "Teacher",   cls: "bg-blue-100 text-blue-700"  },
    assistant: { label: "Assistant", cls: "bg-purple-100 text-purple-700" },
    all:       { label: "All Roles", cls: "bg-green-100 text-green-700" },
  };
  const { label, cls } = map[role];
  return <span className={`text-[11px] font-semibold px-2 py-0.5 rounded-full ${cls}`}>{label}</span>;
}

function AccordionSection({ section, defaultOpen }: { section: SpecSection; defaultOpen?: boolean }) {
  const [open, setOpen] = useState(defaultOpen ?? false);
  const Icon = section.icon;
  return (
    <div className="bg-white rounded-2xl border border-border shadow-sm overflow-hidden">
      <button
        className="w-full flex items-center gap-4 px-5 py-4 text-left hover:bg-gray-50 transition-colors"
        onClick={() => setOpen(v => !v)}
      >
        <div className={`w-9 h-9 rounded-xl bg-gradient-to-br ${section.color} flex items-center justify-center shrink-0`}>
          <Icon className="w-4 h-4 text-white" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="font-bold text-secondary text-sm">{section.title}</h3>
            {section.roles.map(r => <RolePill key={r} role={r} />)}
          </div>
          {!open && (
            <p className="text-xs text-muted-foreground mt-0.5 truncate">{section.overview.slice(0, 90)}…</p>
          )}
        </div>
        <div className="shrink-0 text-muted-foreground">
          {open ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
        </div>
      </button>

      {open && (
        <div className="border-t border-border px-5 py-5 space-y-5 bg-gray-50/40">
          <p className="text-sm text-muted-foreground leading-relaxed">{section.overview}</p>

          {section.steps && section.steps.length > 0 && (
            <div>
              <h4 className="text-xs font-bold text-secondary uppercase tracking-wider mb-3">How it works</h4>
              <ol className="space-y-3">
                {section.steps.map((s, i) => (
                  <li key={i} className="flex gap-3">
                    <div className={`w-6 h-6 rounded-full bg-gradient-to-br ${section.color} text-white text-xs font-bold flex items-center justify-center shrink-0 mt-0.5`}>
                      {i + 1}
                    </div>
                    <div>
                      <span className="text-sm font-semibold text-secondary">{s.heading} — </span>
                      <span className="text-sm text-muted-foreground">{s.detail}</span>
                    </div>
                  </li>
                ))}
              </ol>
            </div>
          )}

          {section.tips && section.tips.length > 0 && (
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
              <h4 className="text-xs font-bold text-amber-800 uppercase tracking-wider mb-2">💡 Tips</h4>
              <ul className="space-y-1.5">
                {section.tips.map((t, i) => (
                  <li key={i} className="text-xs text-amber-900 flex gap-2">
                    <span className="shrink-0">•</span>
                    <span>{t}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {section.notes && section.notes.length > 0 && (
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
              <h4 className="text-xs font-bold text-blue-800 uppercase tracking-wider mb-2">📌 Important Notes</h4>
              <ul className="space-y-1.5">
                {section.notes.map((n, i) => (
                  <li key={i} className="text-xs text-blue-900 flex gap-2">
                    <span className="shrink-0">•</span>
                    <span>{n}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function Help() {
  const { user } = useAuth();
  const [search, setSearch]     = useState("");
  const [roleFilter, setRoleFilter] = useState<"all" | "admin" | "teacher" | "assistant">("all");
  const [expandAll, setExpandAll] = useState(false);

  const userRole = user?.role ?? "admin";

  function isVisible(s: SpecSection) {
    const roleMatch =
      roleFilter === "all"
        ? s.roles.includes("all") || s.roles.includes(userRole as Role) || s.roles.some(r => r === roleFilter)
        : s.roles.includes("all") || s.roles.includes(roleFilter as Role);
    const q = search.toLowerCase();
    const textMatch = !q ||
      s.title.toLowerCase().includes(q) ||
      s.overview.toLowerCase().includes(q) ||
      s.steps?.some(st => st.heading.toLowerCase().includes(q) || st.detail.toLowerCase().includes(q)) ||
      s.tips?.some(t => t.toLowerCase().includes(q));
    return roleMatch && textMatch;
  }

  const visible = SECTIONS.filter(isVisible);

  const ROLE_FILTER_OPTS = [
    { value: "all",       label: "All Roles" },
    { value: "admin",     label: "Admin only" },
    { value: "teacher",   label: "Teacher / Assistant" },
  ] as const;

  return (
    <div className="space-y-6 max-w-4xl mx-auto">

      {/* ── Hero ──────────────────────────────────────────────────────── */}
      <div className="rounded-2xl overflow-hidden shadow-sm"
        style={{ background: "linear-gradient(135deg, #92400e 0%, #d97706 60%, #fbbf24 100%)" }}>
        <div className="px-6 py-8 flex gap-5 items-center">
          <div className="w-16 h-16 rounded-2xl bg-white/20 flex items-center justify-center text-4xl shrink-0 select-none">
            🪗
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white mb-1">Help & Functional Guide</h1>
            <p className="text-amber-100 text-sm max-w-lg leading-relaxed">
              Welcome to Narad Ji's guide to the Gurukul Admin Portal. Everything you need to know about every feature — written clearly, step by step. Use the search or role filter to find what you need.
            </p>
          </div>
        </div>
        <div className="px-6 pb-5">
          <div className="bg-white/15 rounded-xl px-4 py-2.5 text-amber-100 text-xs leading-relaxed">
            <strong className="text-white">Quick tip:</strong> The 🪗 Narad Ji bot (bottom-right of every page) can answer questions instantly — just type your question. This page contains the full specification with step-by-step instructions.
          </div>
        </div>
      </div>

      {/* ── Filters ───────────────────────────────────────────────────── */}
      <div className="bg-white rounded-2xl border border-border shadow-sm px-5 py-4 flex flex-wrap gap-3 items-center">
        <div className="relative flex-1 min-w-[180px]">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <input
            className="w-full pl-9 pr-4 py-2 text-sm border border-border rounded-xl focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary"
            placeholder="Search features…"
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
        <div className="flex gap-1.5">
          {ROLE_FILTER_OPTS.map(opt => (
            <button
              key={opt.value}
              onClick={() => setRoleFilter(opt.value)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all ${
                roleFilter === opt.value
                  ? "bg-secondary text-white border-secondary"
                  : "border-border text-muted-foreground hover:border-secondary/50 hover:text-secondary"
              }`}
            >
              {opt.label}
            </button>
          ))}
        </div>
        <button
          onClick={() => setExpandAll(v => !v)}
          className="ml-auto text-xs text-primary underline underline-offset-2 hover:text-primary/80 transition-colors whitespace-nowrap"
        >
          {expandAll ? "Collapse all" : "Expand all"}
        </button>
        <span className="text-xs text-muted-foreground">
          {visible.length} of {SECTIONS.length} sections
        </span>
      </div>

      {/* ── Sections ──────────────────────────────────────────────────── */}
      {visible.length === 0 ? (
        <div className="text-center py-16 text-muted-foreground">
          <HelpCircle className="w-12 h-12 mx-auto mb-3 opacity-30" />
          <p className="font-medium">No sections match your search</p>
          <p className="text-sm mt-1">Try different keywords or clear the filter.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {visible.map(s => (
            <AccordionSection key={s.id} section={s} defaultOpen={expandAll} />
          ))}
        </div>
      )}

      {/* ── Footer note ───────────────────────────────────────────────── */}
      <div className="bg-amber-50 border border-amber-200 rounded-2xl px-5 py-4 text-sm text-amber-800 text-center">
        🙏 <strong>Narayan Narayan!</strong> Still have questions? Click the <strong>🪗</strong> button at the bottom-right of any page to chat with Narad Ji directly.
      </div>
    </div>
  );
}
